config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from account import views

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

import account

urlpatterns = [
    # Django authentication
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('signup/', views.SignUpUser.as_view(), name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),

    path('3ecret@dminp@nel/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('todo.urls', namespace='todo')),
    path('', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = account.views.error_404

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

todo/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),
    path('account/current/todo/', views.CurrentToDoList.as_view(), name='current_todo'),
    path('account/complete/todo/', views.CompleteToDoList.as_view(), name='complete_todo'),
    path('account/dashboard/', login_required(TemplateView.as_view(template_name="account/dashboard.html")), name='dashboard'),
    path('account/todo/add/', views.ToDoCreate.as_view(), name='todo_create'),
    path('account/todo/<int:pk>/edit/', views.ToDoUpdate.as_view(), name='todo_update'),
    path('account/todo/<int:pk>/detail/', views.TodoDetail.as_view(), name='todo_detail'),
    path('account/todo/<int:pk>/delete/', views.ToDoDelete.as_view(), name='todo_delete'),
    path('account/todo/<int:pk>/complete/', views.complete_todo, name='completetodo'),
]

contact/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from random import randint


class ToDo(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    title = models.CharField(max_length=100, verbose_name='عنوان')
    memo = models.TextField(blank=True, null=True, verbose_name='توضیحات')
    important = models.BooleanField(default=False, verbose_name='مهم')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    datecomplete = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ کامل شدن')

    class Meta:
        verbose_name = 'تودو'
        verbose_name_plural = 'تودوها'

    def __str__(self):
        return self.title

    def save(self):
        if not self.id:
            is_unique = False
            while not is_unique:
                id = randint(1000000000000000000, 1999999999999999999) # 19 digits: 1, random 18 digits
                is_unique = not ToDo.objects.filter(id=id).exists()
            self.id = id
        super(ToDo, self).save()

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, required=True, label='نام')
    email = forms.EmailField(required=True, label='ایمیل', help_text='پاسخ شما به این ایمیل ارسال خواهد شد.')
    subject = forms.CharField(max_length=100, required=True, label='موضوع')
    message = forms.CharField(widget=forms.Textarea, required=True, label='پیام شما')

todo/forms.py
from django import forms

from .models import ToDo

class ToDoForm(forms.ModelForm):
    
    class Meta:
        model = ToDo
        fields = ['title', 'memo', 'important']

contact/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ContactForm

# Create your views here.

def contact(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = f"موضوع: {form.cleaned_data['subject']}"
            message = f"اسم: {name}\nپیام: {form.cleaned_data['message']} \n {email}"
            try:
                messages.success(request, 'ایمیل شما با موفقیت ارسال شد. درکوتاه ترین زمان ممکن به شما پاسخ داده خواهد شد.')
                send_mail(subject=subject, message=message, from_email=email, recipient_list=['todomanager04@gmail.com'])
            except BadHeaderError:
                return HttpResponse("ایمیل شما ارسال نشد!")
            return redirect('contact:contact')
    return render(request, 'contact/contact_form.html', {'form': form})

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.detail import DetailView


from .models import ToDo
from .mixins import OwnerToDoMixin, OwnerToDoEditMixin, OwnerMixin

# Create your views here.

def home(request):
    return render(request, 'todo/home.html')


class CurrentToDoList(ListView):
    paginate_by = 5
    def get_queryset(self):
        return ToDo.objects.filter(user=self.request.user, datecomplete__isnull=True)
    template_name = 'todo/current.html'


class CompleteToDoList(ListView):
    paginate_by = 5
    def get_queryset(self):
        return ToDo.objects.filter(user=self.request.user, datecomplete__isnull=False)
    template_name = 'todo/complete.html'


class TodoDetail(LoginRequiredMixin, OwnerMixin, DetailView):
    model = ToDo


class ToDoCreate(SuccessMessageMixin, OwnerToDoEditMixin, CreateView):
    success_message = "تودو با موفقیت ایجاد شد."


class ToDoUpdate(SuccessMessageMixin, OwnerToDoEditMixin, UpdateView):
    success_message = "تودو با موفقیت ویرایش شد."


class ToDoDelete(SuccessMessageMixin, OwnerToDoMixin, DeleteView):
    template_name = 'todo/delete-todo.html'


@login_required
def complete_todo(request, pk):
    todo = get_object_or_404(ToDo, id=pk, user=request.user)
    if request.method == "POST":
        todo.datecomplete = timezone.now()
        todo.save()
        messages.success(request, 'تودو با موفقیت کامل شد.')
        return redirect('todo:dashboard')
    else:
        messages.error(request, 'تودو کامل نشد.')
        return redirect('todo:dashboard')

contact/templates/contact/contact_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}تماس باما{% endblock %}

{% block content %}
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-flex align-items-center justify-content-between my-4">
                        <h1 class="h3 mb-0 text-gray-800 mx-auto IranBold">تماس با ما</h1>
                    </div>
                    <div class="col-xl-10 col-lg-7 mx-auto">
                        {% if messages %}
                            <div class="alert alert-primary alert-dismissible fade show text-right shadow rounded" role="alert">
                                {% for message in messages %}
                                    <p{% if message.tags %} class="{{ message.tags }} my-0"{% endif %}><i class="fa fa-check-circle" aria-hidden="true"></i> {{ message }}</p>
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-xl-10 mx-auto text-right">
                        <div class="card shadow mb-4">
                            <!-- Card Header -->
                            <div class="card-header py-3 d-flex bg-primary flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-light IranBold">تماس با ما</h6>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <form method="post" class="needs-validation" novalidate>
                                    {% csrf_token %}
                                    
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            {% if request.user.is_authenticated %}
                                                <div id="div_id_name" class="form-btn-group-toggle">
                                                    <label for="id_name" class="requiredField">
                                                        نام<span class="asteriskField">*</span>
                                                    </label>
                                                    <input type="text" name="name" maxlength="50" class="textinput textInput form-control" required="" id="id_name" value="{{ request.user.get_full_name }}">
                                                </div>
                                            {% else %}
                                                {{ form.name|as_crispy_field }}
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6">
                                            {% if request.user.is_authenticated %}
                                                <div id="div_id_email" class="form-group">
                                                    <label for="id_email" class=" requiredField">
                                                        ایمیل<span class="asteriskField">*</span>
                                                    </label>
                                                    <div class="">
                                                        <input type="email" name="email" class="emailinput form-control" value="{{ request.user.email }}" required="" id="id_email">
                                                        <small id="hint_id_email" class="form-text text-muted">پاسخ شما به این ایمیل ارسال خواهد شد.</small>
                                                    </div>
                                                </div>
                                            {% else %}
                                                {{ form.email|as_crispy_field }}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            {{ form.subject|as_crispy_field }}
                                        </div>
                                        <div class="col-md-12">
                                            {{ form.message|as_crispy_field }}
                                        </div>
                                    </div>
                                    <button class="btn btn-primary btn-block IranBold" type="submit">ارسال</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
{% endblock %}

todo/templates/todo/create-update-todo.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load jalali_tags %}

{% block title %}
    {% if object %}
        ویرایش « {{ object.title }} »
    {% else %}
        ایجاد کار جدید
    {% endif %}
{% endblock %}

{% block content %}
    <div id="wrapper">

        {% include 'account/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include 'account/top_navbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800 mx-auto IranBold text-center">
                            {% if object %}
                                <div>ویرایش « {{ object.title }} »</div>
                                <hr>
                                <div class="text-muted small mt-2">تاریخ ایجاد:‌ {{ object.created|to_jalali:'14%y/%m/%d' }}</div>
                            {% else %}
                                ایجاد کار جدید
                            {% endif %}
                        </h1>
                    </div>
                    
                    <div class="col-xl-10 col-lg-7 mx-auto text-right">
                        <div class="card shadow mb-4">
                            <!-- Card Header -->
                            <div class="card-header py-3 d-flex bg-primary flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-light IranBold">
                                    {% if object %}
                                        ویرایش کار
                                    {% else %}
                                        ایجاد کار جدید
                                    {% endif %}
                                </h6>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <form method="post" class="needs-validation" novalidate>
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            {{ form.title|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            {{ form.memo|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="form-row mb-4">
                                        <div class="col-md-12">
                                            <label for="id_important" class="form-check-label ml-3">
                                                مهم
                                            </label>
                                            <input type="checkbox" name="important" class="checkboxinput form-check-input" id="id_important">
                                        </div>
                                    </div>
                                    <button class="btn btn-primary btn-block IranBold" type="submit">ذخیره</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
{% endblock %}

todo/templates/todo/current.html
{% extends 'base.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست تودوها{% endblock %}

{% block content %}
    <div id="wrapper">

        {% include 'account/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column IranBold">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include 'account/top_navbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">لیست کارهای حاضر</h1>
                    </div>

                    <!-- Content Row -->

                    <div class="row">
                        <!-- ُTodo List -->
                        <div class="col-xl-12">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">لیست کارهای حاضر</h6>
                                    
                                </div>
                                <!-- Card Body -->
                                <div class="card-body text-center">
                                    {% if object_list %}
                                        <div class="table-responsive rounded">
                                            <table class="table table-hover">
                                                <thead class="text-white bg-info">
                                                    <tr>
                                                        <th scope="col" style="width: 25%">عنوان</th>
                                                        <th scope="col" style="width: 45%">توضیحات</th>
                                                        <th scope="col" style="width: 5%">مهم</th>
                                                        <th scope="col" style="width: 25%"> </th>
                                                    </tr>
                                                </thead>
                                                <tbody class="sfont">
                                                    {% for todo in object_list %}
                                                        <tr {% if todo.important %} class="table-danger"{% endif %}>
                                                            <td>{{ todo.title }}</td>
                                                            {% if todo.memo %}
                                                                <td>
                                                                    <details>
                                                                        <summary>توضیحات</summary>
                                                                        <p>{{ todo.memo }}</p>
                                                                    </details>
                                                                </td>
                                                            {% else %}
                                                                <td></td>
                                                            {% endif %}
                                                            {% if todo.important %} 
                                                                <td>*</td> 
                                                            {% else %}
                                                                <td></td>
                                                            {% endif %}
                                                            <td>
                                                                {% if not todo.datecomplete %}
                                                                    <a class="btn btn-sm btn-primary font-weight-bold mb-2 mb-lg-0" href="{% url 'todo:todo_update' todo.pk %}" style="padding: 5px 15px;">ویرایش</a>
                                                                {% endif %}
                                                                    <a class="btn btn-sm btn-danger font-weight-bold mb-2 mb-lg-0 " href="{% url 'todo:todo_delete' todo.pk %}" style="padding: 5px 20px;">حذف</a>
                                                                {% if todo.datecomplete is None %}
                                                                    <form class="d-inline " method="POST" action="{% url 'todo:completetodo' todo.pk %}">
                                                                        {% csrf_token %}
                                                                        <button class="btn btn-success btn-sm font-weight-bold mb-2 mb-lg-0" id="complete" type="submit" style="padding: 5px 18px;">تکمیل</button>
                                                                    </form>
                                                                {% else %}
                                                                    <div class="badge badge-info font-weight-bold " style="padding: 10px 15px;"><span>کامل شد</span></div>
                                                                {% endif %}
                                                            </td>
                                                        </tr>                                                  
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    {% else %}
                                        <div class="alert alert-info">
                                            <span>شما در حال حاضر کاری برای انجام دادن ندارید.</span>
                                        </div>
                                            <a href="{% url 'todo:todo_create' %}" class="btn btn-primary btn-block">اضافه کردن </a>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Paginator -->
                            {% if is_paginated %}
                                <nav dir='ltr' aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                                        {% endif %}
                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="active page-item">
                                                    <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span><a href='https://github.com/karimi79younes/ToDo_Project_FA.git' target="_blank" class="text-dark">سورس کد</a></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
{% endblock %}

todo/templates/todo/todo_list_templatetags.html
{% load humanize %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">{{ title }}</h6>
        
    </div>
    <!-- Card Body -->
    <div class="card-body text-center">
        {% if latest_todos %}
            <div class="table-responsive rounded">
                <table class="table table-hover">
                    <thead class="text-white bg-info">
                        <tr>
                            <th scope="col">عنوان</th>
                            <th scope="col">
                                {{ theader }}
                            </th>
                            <th scope="col"> </th>
                        </tr>
                    </thead>
                    <tbody class="sfont">
                        {% for todo in latest_todos %}
                            <tr {% if todo.important %} class="table-danger"{% endif %}>
                                <td>{{ todo.title }}</td>
                                {% if todo.created %}
                                    <td>{{ todo.created|naturaltime }}</td>
                                {% else %}
                                    <td>{{ todo.datecomplete|naturaltime }}</td>
                                {% endif %}
                                <td>
                                    {% if not todo.datecomplete %}
                                        <a class="btn btn-sm btn-primary font-weight-bold mb-2 mb-md-0" href="{% url 'todo:todo_update' todo.pk %}" style="padding: 5px 15px;">ویرایش</a>
                                    {% endif %}
                                        <a class="btn btn-sm btn-danger font-weight-bold mb-2 mb-md-0 " href="{% url 'todo:todo_delete' todo.pk %}" style="padding: 5px 20px;">حذف</a>
                                    {% if todo.datecomplete is None %}
                                        <form class="d-inline " method="POST" action="{% url 'todo:completetodo' todo.pk %}">
                                            {% csrf_token %}
                                            <button class="btn btn-success btn-sm font-weight-bold mb-2 mb-md-0" id="complete" type="submit" style="padding: 5px 18px;">تکمیل</button>
                                        </form>
                                    {% else %}
                                        <a href="#" class="disabled btn btn-info btn-sm font-weight-bold mb-2 mb-md-0" style="padding: 5px 10px;"><span>کامل شد</span></a>
                                    {% endif %}
                                </td>
                            </tr>                                                  
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div class="alert alert-info">
                <span>{{ alert }}</span>
            </div>
        {% endif %}
    </div>
</div>